package com.karrycode.cfpolsbackend;

import lombok.extern.slf4j.Slf4j;
import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@Slf4j
@SpringBootApplication
@MapperScan("com.karrycode.cfpolsbackend.mapper")
public class CfPolsBackendApplication {

    public static void main(String[] args) {
        SpringApplication.run(CfPolsBackendApplication.class, args);
    }

}
